
title-bold: Infini
title-normal: Femmes
title: Infini Femmes
email: volatiana.landre@gmail.com
nospammail: contact@infinifemmes.com
description: Coaching Postural, Yoga pré et post natal,<br/> Abdologie, Méthode de Gasquet<br/><br/> Une offre créée par et pour les femmes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.infinifemmes.com" # the base hostname & protocol for your site, e.g. http://example.com
street_address: 15 avenue Jean Monnet
city: Issy Les Moulineaux
state:
zip_code: 92130
country:
phone: 07 81 50 60 83
mapslink : https://goo.gl/maps/TiMVvb9iau92
instagram_url: https://instagram.com/inifinifemmes
facebook_url : https://www.facebook.com/volatiana.andriambolason.3
twitter_url : https://twitter.com/VolatianaLandre

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Google services
google_analytics: UA-88050318-1


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
