
title-bold: Infini
title-normal: Femmes
title: Infini Femmes
email: volatiana.landre@gmail.com
nospammail: contact@infinifemmes.com
description: Coaching Postural, Yoga pré et post natal,<br/> Abdologie, Méthode de Gasquet<br/><br/> Une offre créée par et pour les femmes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.infinifemmes.com" # the base hostname & protocol for your site, e.g. http://example.com
street_address:
city: Meudon
state:
zip_code: 92190
country:
siretnumber : 51203587400035
phone: 07 81 50 60 83
mapslink : https://goo.gl/maps/QdmDCauytZB2
instagram_url: https://instagram.com/infinifemmes
facebook_url : https://www.facebook.com/Infinifemmes/
twitter_url : https://twitter.com/VolatianaLandre
googleplus_url : https://plus.google.com/109937627922238698030

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Google services
google_analytics: UA-88050318-1


#SEO
twitter:
  username: VolatianaLandre
facebook:
  publisher: https://www.facebook.com/Infinifemmes
social:
  name: Infini Femmes
  links:
    - https://instagram.com/infinifemmes
    - https://twitter.com/VolatianaLandre
    - https://www.facebook.com/Infinifemmes
    - https://plus.google.com/109937627922238698030


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
