title-bold: Infini
title-normal: Femmes
title: Infini Femmes
email: volatiana.landre@gmail.com
description: Coaching Postural, Yoga pré et post natal,<br/> Abdologie, Méthode APOR B. de Gasquet
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
street_address: 15 avenue Jean Monnet
city: Issy Les Moulineaux
state:
zip_code: 92130
country:
phone: 07 81 50 60 83
instagram_url: https://instagram.com/infinifemmes
facebook_url : https://www.facebook.com/volatiana.andriambolason.3

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
